const STRINGS = {
  LOGIN_CAPTION: 'Login',
  ELEMENTS_CAPTION: 'ELEMENTS',
  RESET_PASSWORD_CAPTION: 'Reset Password',
  LOGIN_TOUCHID: 'Login via Touch Id',
  LOGIN_FACEID: 'Login via Face Id',
  RESET_PASSWORD_TEXT: 'Enter your email address that used to login to Approvpay. We will send you an email with a link to reset your password.',
  GLOBAL_ENTERPRISE_SOLUTION_CAPTION: 'Global Enterprise Solutions',
  REVIEW_INVOICE_CAPTION: 'Review Invoices',
  FAVOURITE_REPORT: 'Favourite Report',
  ACTIVE_EMPLOYEES_CAPTION: 'Total Number\nof Active Employees',
  SETTINGS_CAPTION: 'Settings',
  CHOOSE_LOGIN_OPTION_CAPTION: 'Choose Your Login Options',
  FACEID_CAPTION: 'Face ID',
  TOUCHID_CAPTION: 'Touch ID',
  LOGOUT_CAPTION: 'Log Out',
  OPEN_TASK_CAPTION: 'Open Tasks',
  NOTIFICATION_CAPTION: 'Notifications',
  EMPLOYEE_COST_CAPTION:'Total Employee Cost',
  PER_MONTH_CAPTION:'per Month in USD',
  EMAIL_CAPTION:'Email',
  ERROR_CAPTION:'Error',
  OKAY_CAPTION:'Okay',
  EMAIL_VALIDATION_MESSAGE: 'Email field cannot be empty',
  EMAIL_VALIDATION_MESSAGE_INCORRECT:'Email field is incorrect',
  VALID_EMAIL_CAPTION:'Enter Valid Email',
  REMEMBER_ME_CAPTION:'Remember me',
  OLDER_TXT_CAPTION:'Older',
  LOGIN_TXT_CAPTION:'Log In',
  FORGET_PASSWORD_CAPTION:'Forgot password?',
  FORGET_PASSWORD_VALIDATION:'Password must be 6 characters long',
  PASSWORD_CAPTION:'Password',
  MYREPORT_CAPTION:'My Reports',
  FAVOURITE_REPORT_CAPTION:'Favorite Report',
  OTHER_REPORT_CAPTION:'Other Reports',
  DOMAIN_CAPTION:'Enter Domain',
  MY_DOMAIN_CAPTION:'What is my domain?',
  YOUR_DOMAIN_CAPTION:'your domain',
  COMPANY_DOMAIN_CAPTION:'company domain',
  DOMAIN_WISHES:'Good Morning!',
  VALID_DOMAIN_CAPTION:'Enter valid domain',
  CONTINUE_TXT_CAPTION:'Continue',
  DOMAIN_VALIDATION_MESSAGE: 'Domain field cannot be empty',
  APPROV_DOMAIN_CAPTION:'.approvpay.com',
  CHANGE_DOMAIN:'Change Domain',
};

export default STRINGS;
